/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qualixium.playnb.nodes.sbtdependencies;

import com.qualixium.playnb.PlayProject;
import com.qualixium.playnb.filetype.sbt.format.SBTReformatTask;
import com.qualixium.playnb.nodes.sbtdependencies.Dependency.Scope;
import com.qualixium.playnb.project.general.PlayPanel;
import static com.qualixium.playnb.project.general.PlayPanel.SBT_INDENT_SPACES;
import com.qualixium.playnb.util.ExceptionManager;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import org.openide.awt.StatusDisplayer;
import org.openide.filesystems.FileObject;
import org.openide.util.NbPreferences;

/**
 *
 * @author pedro
 */
public class AddDependencyDialog extends javax.swing.JDialog {

    /**
     * Creates new form AddDependencyDialog
     */
    public AddDependencyDialog(java.awt.Frame parent, boolean modal,
            SBTDependenciesParentNode parentNode, PlayProject playProject) {
        super(parent, modal);
        this.parentNode = parentNode;
        this.playProject = playProject;
        initComponents();
        myOwnInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        tab = new javax.swing.JTabbedPane();
        mvnDepPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDependencies = new javax.swing.JList();
        lblSearchInfo = new javax.swing.JLabel();
        btnAddDependency = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jxSearchField = new org.jdesktop.swingx.JXSearchField();
        lblBusy = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelArtifactInfo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGroupId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtArtifactId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtVersion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbxScope = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.title")); // NOI18N
        setAlwaysOnTop(true);

        mainPanel.setToolTipText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.mainPanel.toolTipText")); // NOI18N

        mvnDepPanel.setToolTipText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.mainPanel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jLabel5.text")); // NOI18N

        jListDependencies.setModel(listModel);
        jListDependencies.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListDependencies.setToolTipText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.mainPanel.toolTipText")); // NOI18N
        jListDependencies.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jListDependenciesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jListDependencies);

        lblSearchInfo.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        lblSearchInfo.setForeground(new java.awt.Color(0, 102, 0));
        org.openide.awt.Mnemonics.setLocalizedText(lblSearchInfo, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.lblSearchInfo.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(btnAddDependency, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.btnAddDependency.text")); // NOI18N
        btnAddDependency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDependencyActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(btnCancel, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jxSearchField.setText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jxSearchField.text")); // NOI18N
        jxSearchField.setToolTipText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jxSearchField.toolTipText")); // NOI18N
        jxSearchField.setInstantSearchDelay(500);
        jxSearchField.setPrompt(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jxSearchField.prompt")); // NOI18N
        jxSearchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jxSearchFieldActionPerformed(evt);
            }
        });

        lblBusy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qualixium/playnb/busy_icon.gif"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblBusy, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.lblBusy.text")); // NOI18N
        lblBusy.setOpaque(true);

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jLabel6.text")); // NOI18N

        javax.swing.GroupLayout mvnDepPanelLayout = new javax.swing.GroupLayout(mvnDepPanel);
        mvnDepPanel.setLayout(mvnDepPanelLayout);
        mvnDepPanelLayout.setHorizontalGroup(
            mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mvnDepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mvnDepPanelLayout.createSequentialGroup()
                        .addGroup(mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(mvnDepPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mvnDepPanelLayout.createSequentialGroup()
                                        .addGap(166, 166, 166)
                                        .addComponent(lblBusy, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jxSearchField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(mvnDepPanelLayout.createSequentialGroup()
                        .addComponent(btnAddDependency)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addGap(36, 36, 36))
                    .addComponent(lblSearchInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        mvnDepPanelLayout.setVerticalGroup(
            mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mvnDepPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jxSearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBusy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSearchInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(mvnDepPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDependency)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        tab.addTab(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.mvnDepPanel.TabConstraints.tabTitle"), mvnDepPanel); // NOI18N

        panelArtifactInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.panelArtifactInfo.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jLabel1.text")); // NOI18N

        txtGroupId.setText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.txtGroupId.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jLabel2.text")); // NOI18N

        txtArtifactId.setText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.txtArtifactId.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jLabel3.text")); // NOI18N

        txtVersion.setText(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.txtVersion.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.jLabel4.text")); // NOI18N

        cbxScope.setModel(dcm);

        javax.swing.GroupLayout panelArtifactInfoLayout = new javax.swing.GroupLayout(panelArtifactInfo);
        panelArtifactInfo.setLayout(panelArtifactInfoLayout);
        panelArtifactInfoLayout.setHorizontalGroup(
            panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtifactInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGroupId)
                    .addComponent(txtArtifactId)
                    .addComponent(txtVersion)
                    .addComponent(cbxScope, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelArtifactInfoLayout.setVerticalGroup(
            panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelArtifactInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtArtifactId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelArtifactInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbxScope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelArtifactInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelArtifactInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab)
                .addContainerGap())
        );

        tab.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(AddDependencyDialog.class, "AddDependencyDialog.tab.AccessibleContext.accessibleName")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListDependenciesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jListDependenciesValueChanged
        if (jListDependencies.getSelectedValue() != null) {
            Dependency dependency = (Dependency) jListDependencies.getSelectedValue();
            txtGroupId.setText(dependency.groupId);
            txtArtifactId.setText(dependency.artifactId);
            txtVersion.setText(dependency.version);
        }
    }//GEN-LAST:event_jListDependenciesValueChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddDependencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDependencyActionPerformed
        try {
            String groupId = txtGroupId.getText();
            String artifactId = txtArtifactId.getText();
            String version = txtVersion.getText();
            Scope scopeSelected = (Scope) dcm.getSelectedItem();
            Dependency dependencyDTO = new Dependency(groupId, artifactId, version, scopeSelected);
            FileObject foBuildSBT = playProject.getProjectDirectory().getFileObject("build.sbt");

            String fileWithDependencyAdded = BuildSBTManager.GetNewFileContentWithDependencyAdded(foBuildSBT.asText(), dependencyDTO);

            int sbtIndentSpaces = NbPreferences.forModule(PlayPanel.class).getInt(SBT_INDENT_SPACES, 4);
            String newFileContent = SBTReformatTask.formatFile(fileWithDependencyAdded, sbtIndentSpaces);

            Files.write(Paths.get(foBuildSBT.toURI()),
                    newFileContent.getBytes());

            StatusDisplayer.getDefault().setStatusText("Dependency: " + dependencyDTO + " added to build.sbt");

            parentNode.reloadChildrens();
            this.dispose();
        } catch (IOException ex) {
            ExceptionManager.logException(ex);
        }
    }//GEN-LAST:event_btnAddDependencyActionPerformed

    private void jxSearchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jxSearchFieldActionPerformed
        String text = jxSearchField.getText();
        if (text.length() >= 3) {
            listModel.clear();
            lblBusy.setVisible(true);
            lblSearchInfo.setVisible(false);

            new SearchDepByQuerSwingWorker(this, text).execute();
        }
    }//GEN-LAST:event_jxSearchFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDependency;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox cbxScope;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jListDependencies;
    private javax.swing.JScrollPane jScrollPane1;
    private org.jdesktop.swingx.JXSearchField jxSearchField;
    private javax.swing.JLabel lblBusy;
    private javax.swing.JLabel lblSearchInfo;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel mvnDepPanel;
    private javax.swing.JPanel panelArtifactInfo;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField txtArtifactId;
    private javax.swing.JTextField txtGroupId;
    private javax.swing.JTextField txtVersion;
    // End of variables declaration//GEN-END:variables
    private final SBTDependenciesParentNode parentNode;
    private final PlayProject playProject;
    private final DefaultListModel<Dependency> listModel = new DefaultListModel<>();
    private DefaultComboBoxModel<Scope> dcm = new DefaultComboBoxModel<>();

    private void myOwnInitComponents() {
        jxSearchField.requestFocus();
        lblBusy.setVisible(false);
        lblSearchInfo.setVisible(false);
        for (Scope scope : Scope.values()) {
            dcm.addElement(scope);
        }
    }

    public JLabel getLblSearchInfo() {
        return lblSearchInfo;
    }

    public DefaultListModel<Dependency> getListModel() {
        return listModel;
    }

    public JLabel getLblBusy() {
        return lblBusy;
    }

}
