/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qualixium.playnb.template.scala.ftspecs2;

import com.qualixium.playnb.PlayProject;
import com.qualixium.playnb.template.TemplateUtil;
import com.qualixium.playnb.util.MiscUtil.Language;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.JTextComponent;
import org.netbeans.api.project.Project;
import org.netbeans.spi.project.ui.templates.support.Templates;
import org.openide.WizardDescriptor;
import org.openide.filesystems.FileObject;

public final class FTSpecs2VisualPanel1 extends JPanel {

    private final WizardDescriptor wizard;

    public FTSpecs2VisualPanel1(WizardDescriptor wizard) {
        this.wizard = wizard;
        initComponents();
        myOwnInitComponents();
    }

    @Override
    public String getName() {
        return "Name and Location";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCreatedFile = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtProjectName = new javax.swing.JTextField();
        cbxPackageName = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, "Name:");

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, "Package:");

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, "Created File:");

        txtCreatedFile.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, "Project: ");

        txtProjectName.setEditable(false);

        cbxPackageName.setEditable(true);
        cbxPackageName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addComponent(txtCreatedFile)
                    .addComponent(txtProjectName)
                    .addComponent(cbxPackageName, 0, 390, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxPackageName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCreatedFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        updateCreatedFileText();
    }//GEN-LAST:event_txtNameKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxPackageName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCreatedFile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtProjectName;
    // End of variables declaration//GEN-END:variables
    private void myOwnInitComponents() {
        Project project = Templates.getProject(wizard);
        JTextComponent comp = (JTextComponent) cbxPackageName.getEditor().getEditorComponent();
        comp.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCreatedFileText();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCreatedFileText();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                updateCreatedFileText();
            }
        });

        txtProjectName.setText(((PlayProject) project).getProjectName());

        txtName.setText("NewSpec");

        FileObject foTargetFolder = Templates.getTargetFolder(wizard);
        String currentPackageName = TemplateUtil.cleanTargetFolder(foTargetFolder, project);

        if (currentPackageName.startsWith(".")) {
            currentPackageName = currentPackageName.substring(1);
        }

        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        List<String> packagesName = TemplateUtil.getPackagesName(project.getProjectDirectory().getPath() + "/app");
        packagesName.stream().forEach((packageName) -> {
            model.addElement(packageName);
        });

        cbxPackageName.setModel(model);
        cbxPackageName.setSelectedItem(currentPackageName);

        txtName.requestFocus();
        txtName.selectAll();
    }

    public JComboBox getCbxPackageName() {
        return cbxPackageName;
    }

    public JTextField getTxtName() {
        return txtName;
    }

    public JTextField getTxtCreatedFile() {
        return txtCreatedFile;
    }

    private void updateCreatedFileText() {
        TemplateUtil.updateCreatedFileText(wizard, cbxPackageName, txtName, txtCreatedFile, Language.SCALA);
    }

}
