/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package com.qualixium.playnb.filetype.routes.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int GET = 3;
  /** RegularExpression Id. */
  int HEAD = 4;
  /** RegularExpression Id. */
  int POST = 5;
  /** RegularExpression Id. */
  int PUT = 6;
  /** RegularExpression Id. */
  int DELETE = 7;
  /** RegularExpression Id. */
  int TRACE = 8;
  /** RegularExpression Id. */
  int OPTIONS = 9;
  /** RegularExpression Id. */
  int CONNECT = 10;
  /** RegularExpression Id. */
  int PATCH = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int BYTE = 13;
  /** RegularExpression Id. */
  int CHAR = 14;
  /** RegularExpression Id. */
  int FALSE = 15;
  /** RegularExpression Id. */
  int FLOAT = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int LONG = 18;
  /** RegularExpression Id. */
  int SHORT = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 21;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 22;
  /** RegularExpression Id. */
  int HEX_LITERAL = 23;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 24;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 25;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 26;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 27;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 28;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 29;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 30;
  /** RegularExpression Id. */
  int STRING_LITERAL = 31;
  /** RegularExpression Id. */
  int IDENTIFIER = 32;
  /** RegularExpression Id. */
  int LETTER = 33;
  /** RegularExpression Id. */
  int PART_LETTER = 34;
  /** RegularExpression Id. */
  int LPAREN = 35;
  /** RegularExpression Id. */
  int RPAREN = 36;
  /** RegularExpression Id. */
  int LBRACE = 37;
  /** RegularExpression Id. */
  int RBRACE = 38;
  /** RegularExpression Id. */
  int LBRACKET = 39;
  /** RegularExpression Id. */
  int RBRACKET = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int COMMA = 42;
  /** RegularExpression Id. */
  int DOT = 43;
  /** RegularExpression Id. */
  int AT = 44;
  /** RegularExpression Id. */
  int ASSIGN = 45;
  /** RegularExpression Id. */
  int LT = 46;
  /** RegularExpression Id. */
  int BANG = 47;
  /** RegularExpression Id. */
  int TILDE = 48;
  /** RegularExpression Id. */
  int HOOK = 49;
  /** RegularExpression Id. */
  int COLON = 50;
  /** RegularExpression Id. */
  int EQ = 51;
  /** RegularExpression Id. */
  int LE = 52;
  /** RegularExpression Id. */
  int GE = 53;
  /** RegularExpression Id. */
  int NE = 54;
  /** RegularExpression Id. */
  int SC_OR = 55;
  /** RegularExpression Id. */
  int SC_AND = 56;
  /** RegularExpression Id. */
  int INCR = 57;
  /** RegularExpression Id. */
  int DECR = 58;
  /** RegularExpression Id. */
  int PLUS = 59;
  /** RegularExpression Id. */
  int MINUS = 60;
  /** RegularExpression Id. */
  int STAR = 61;
  /** RegularExpression Id. */
  int SLASH = 62;
  /** RegularExpression Id. */
  int BIT_AND = 63;
  /** RegularExpression Id. */
  int BIT_OR = 64;
  /** RegularExpression Id. */
  int XOR = 65;
  /** RegularExpression Id. */
  int REM = 66;
  /** RegularExpression Id. */
  int LSHIFT = 67;
  /** RegularExpression Id. */
  int PLUSASSIGN = 68;
  /** RegularExpression Id. */
  int MINUSASSIGN = 69;
  /** RegularExpression Id. */
  int STARASSIGN = 70;
  /** RegularExpression Id. */
  int SLASHASSIGN = 71;
  /** RegularExpression Id. */
  int ANDASSIGN = 72;
  /** RegularExpression Id. */
  int ORASSIGN = 73;
  /** RegularExpression Id. */
  int XORASSIGN = 74;
  /** RegularExpression Id. */
  int REMASSIGN = 75;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 76;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 77;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 78;
  /** RegularExpression Id. */
  int ELLIPSIS = 79;
  /** RegularExpression Id. */
  int BAD_QUOTE = 80;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"GET\"",
    "\"HEAD\"",
    "\"POST\"",
    "\"PUT\"",
    "\"DELETE\"",
    "\"TRACE\"",
    "\"OPTIONS\"",
    "\"CONNECT\"",
    "\"PATCH\"",
    "\"Boolean\"",
    "\"Byte\"",
    "\"Char\"",
    "\"False\"",
    "\"Float\"",
    "\"Int\"",
    "\"Long\"",
    "\"Short\"",
    "\"True\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"`\"",
  };

}
