/* Generated By:JavaCC: Do not edit this line. JavaParserConstants.java */
package com.qualixium.playnb.filetype.conf.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavaParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 3;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 4;
  /** RegularExpression Id. */
  int HEX_LITERAL = 5;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 6;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 7;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 8;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 9;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 10;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 11;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 12;
  /** RegularExpression Id. */
  int STRING_LITERAL = 13;
  /** RegularExpression Id. */
  int IDENTIFIER = 14;
  /** RegularExpression Id. */
  int LETTER = 15;
  /** RegularExpression Id. */
  int PART_LETTER = 16;
  /** RegularExpression Id. */
  int LPAREN = 17;
  /** RegularExpression Id. */
  int RPAREN = 18;
  /** RegularExpression Id. */
  int LBRACE = 19;
  /** RegularExpression Id. */
  int RBRACE = 20;
  /** RegularExpression Id. */
  int LBRACKET = 21;
  /** RegularExpression Id. */
  int RBRACKET = 22;
  /** RegularExpression Id. */
  int SEMICOLON = 23;
  /** RegularExpression Id. */
  int COMMA = 24;
  /** RegularExpression Id. */
  int DOT = 25;
  /** RegularExpression Id. */
  int AT = 26;
  /** RegularExpression Id. */
  int ASSIGN = 27;
  /** RegularExpression Id. */
  int LT = 28;
  /** RegularExpression Id. */
  int BANG = 29;
  /** RegularExpression Id. */
  int TILDE = 30;
  /** RegularExpression Id. */
  int HOOK = 31;
  /** RegularExpression Id. */
  int COLON = 32;
  /** RegularExpression Id. */
  int EQ = 33;
  /** RegularExpression Id. */
  int LE = 34;
  /** RegularExpression Id. */
  int GE = 35;
  /** RegularExpression Id. */
  int NE = 36;
  /** RegularExpression Id. */
  int SC_OR = 37;
  /** RegularExpression Id. */
  int SC_AND = 38;
  /** RegularExpression Id. */
  int INCR = 39;
  /** RegularExpression Id. */
  int DECR = 40;
  /** RegularExpression Id. */
  int PLUS = 41;
  /** RegularExpression Id. */
  int MINUS = 42;
  /** RegularExpression Id. */
  int STAR = 43;
  /** RegularExpression Id. */
  int SLASH = 44;
  /** RegularExpression Id. */
  int BIT_AND = 45;
  /** RegularExpression Id. */
  int BIT_OR = 46;
  /** RegularExpression Id. */
  int XOR = 47;
  /** RegularExpression Id. */
  int REM = 48;
  /** RegularExpression Id. */
  int LSHIFT = 49;
  /** RegularExpression Id. */
  int PLUSASSIGN = 50;
  /** RegularExpression Id. */
  int MINUSASSIGN = 51;
  /** RegularExpression Id. */
  int STARASSIGN = 52;
  /** RegularExpression Id. */
  int SLASHASSIGN = 53;
  /** RegularExpression Id. */
  int ANDASSIGN = 54;
  /** RegularExpression Id. */
  int ORASSIGN = 55;
  /** RegularExpression Id. */
  int XORASSIGN = 56;
  /** RegularExpression Id. */
  int REMASSIGN = 57;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 58;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 59;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 60;
  /** RegularExpression Id. */
  int ELLIPSIS = 61;
  /** RegularExpression Id. */
  int BAD_QUOTE = 62;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"`\"",
  };

}
