/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.qualixium.playnb.project.specific;

import static com.qualixium.playnb.project.specific.ProjectSpecificSettings.*;
import com.qualixium.playnb.util.ExceptionManager;
import com.qualixium.playnb.util.GestureManager;
import java.io.IOException;
import java.util.logging.Level;
import org.netbeans.api.project.Project;

/**
 *
 * @author pedro
 */
public class PanelMainProperties extends javax.swing.JPanel {

    private final Project project;

    /**
     * Creates new form PanelMainProperties
     */
    public PanelMainProperties(Project project) {
        this.project = project;
        initComponents();
        myOwnInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtParameters = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRunPort = new javax.swing.JFormattedTextField();
        txtDebugPort = new javax.swing.JFormattedTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.jLabel1.text")); // NOI18N

        txtParameters.setText(org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.txtParameters.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.jLabel4.text")); // NOI18N
        jLabel4.setOpaque(true);

        txtRunPort.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        txtRunPort.setText(org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.txtRunPort.text")); // NOI18N
        txtRunPort.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        txtDebugPort.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        txtDebugPort.setText(org.openide.util.NbBundle.getMessage(PanelMainProperties.class, "PanelMainProperties.txtDebugPort.text")); // NOI18N
        txtDebugPort.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtParameters)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRunPort, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtRunPort, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDebugPort, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JFormattedTextField txtDebugPort;
    private javax.swing.JTextField txtParameters;
    private javax.swing.JFormattedTextField txtRunPort;
    // End of variables declaration//GEN-END:variables

    public String getDebugPort() {
        return txtDebugPort.getText();
    }

    public String getRunPort() {
        return txtRunPort.getText();
    }

    public String getParameters() {
        return txtParameters.getText();
    }

    private void myOwnInitComponents() {
        GestureManager.registerGesture(Level.INFO, "1- Open Properties Dialog", null);
        try {
            ProjectSpecificSettings settings = new ProjectSpecificSettings(project.getProjectDirectory().getPath());

            txtRunPort.setText(settings.getValue(KEYS_RUN_PORT).orElse("9000"));
            txtDebugPort.setText(settings.getValue(KEYS_DEBUG_PORT).orElse("9999"));
            txtParameters.setText(settings.getValue(KEYS_COMMAND_PARAMETERS).orElse(""));
        } catch (IOException ex) {
            ExceptionManager.logException(ex);
        }
    }

}
