package com.qualixium.playnb.project.newprojectwizard;

public enum ActivatorTemplateEnum {

    ACTIVATOR_GILT_APP("activator-gilt-app", "Gilt Groupe Play Application Template"),
    PLAY_MCWIRE("play-macwire", "Play Framework using Macwire for dependency injection"),
    PLAY_SILHOUETTE_POSTGRES("play-silhouette-postgres-async-seed", "Play Silhouette Postgres Async Seed"),
    HMRC_FRONTEND("hmrc-frontend", "HMRC Frontend application"),
    PLAY_REACTIVEMONGO_POLYMER("play-reactivemongo-polymer", "Play Framework with REST, ReactiveMongo and Polymer"),
    SALESFORCE_DEVELOPER_WORKSHOP_JAVA("salesforce-developer-workshop-java", "Salesforce Developer Workshop for Java"),
    SIX_MINUTES_APPS("six-minute-apps", "6 Minute Apps!"),
    PLAY_SPRING_DATA_JPA("play-spring-data-jpa", "Play with Spring Data Jpa"),
    MODERN_WEB_TEMPLATE("modern-web-template", "AngularJS Play Mongo"),
    JQUERYTABLECONTENTSPOSTANDFILEDOWNLOAD("jqueryTableContentsPostAndFileDownload", "POST Table Contents with jQuery-Ajax - Convert - Download Excel File"),
    COMPUTER_DATABASE_SCALA("computer-database-scala", "Computer Database Scala"),
    PLAY_MONAD_TRANSFORMERS("play-monad-transformers", "Play Framework with Scalaz monad transformers"),
    PLAY_ITERATEES("play-iteratees", "Play Iteratees"),
    PLAY_SCALA_INTRO("play-scala-intro", "Play Scala Intro"),
    PLAY_SCALAJS_SHOWCASE("play-scalajs-showcase", "Play with Scala.js showcase"),
    PLAY_ENTITYTLED_SIMPLE("play-entitytled-simple", "Play Framework with Entitytled"),
    PLAY_SIMPLE_WEB("play-simple-web", "Play Simple Web Template"),
    INNO_PLAYGROUND("inno-playground", "Blank project with dependencies and test harness. Ready for flubbing."),
    PLAY_AKKA_ANGULAR_WEBSOCKET("play-akka-angular-websocket", "Play Akka Angular WebSocket"),
    PLAY_JAVA_REACTIVE_PLATFORM_15V09("play-java-reactive-platform-15v09", "Play Java Seed (Reactive Platform 15v09)"),
    PLAY_AUTHENTICATE_MONGO("play-authenticate-mongo", "PlayAuthenticate Mongo Sample"),
    PLAY_IMAGE_PROCESSING_CLASSIFICATION("play-image-processing-classification", "Image Processing & Classification Webservice Template"),
    PLAY_JAVA_SPRING_JINQ("play-java-spring-jinq", "Play Java with Spring & Jinq"),
    PLAY_SQLITE("play-sqlite", "Play SQLite (Scala)"),
    REACTIVE_MICROSERVICES("reactive-microservices", "Microservices - reactive communication patterns"),
    SIMPLE_REST_SCALA("simple-rest-scala", "Simple REST API working in Play"),
    SLIM_PLAY_SCALA("slim-play-scala", "Slim Play Scala Seed"),
    REACTIVE_SALESFORCE_REST_ANGULAR_CRUD("reactive-salesforce-rest-angular-crud", "Reactive Salesforce REST Example"),
    DWWS_TEST1("dwws-test1", "Sample application and tutorial for a course class."),
    PLAYING_MICROSERVICES("playing-microservices", "Microservice architecture in Play 2.4.x with Scala"),
    TYPESAFE_EMOJR("typesafe-emojr", "Typesafe Emojr"),
    EVENTUAL("eventual", "The Eventual PlayFramework-AngularJS-Bootstrap-MongoDB Seed Project"),
    PLAY_JAVA_2_3("play-java-2.3", "Play 2.3 Java Seed"),
    REACTIVE_PLAY_SCALA_AKKA_SLICK_GUICE_DOMAIN_VALIDATION_SEED("reactive-play-scala-akka-slick-guice-domain_validation-seed", "Reactive Play, Scala, Slick, Akka Actors, Flyway, JWT Token authentication, Guice DI, DDD Domain validation seed"),
    PLAY_WEBRTC("play-webrtc", "Play WebRTC relay server"),
    PLAY_EXAMPLE_FORM("play-example-form", "Play Example Form"),
    PLAYSECURESOCIAL("playSecureSocial", "Seed for Play with SecureSocial and Jooq"),
    PLAY_SCALATEST_SUBCUT("play-scalatest-subcut", "Play Framework using Scalatest for testing and SubCut for configuration"),
    PLAY2BARS_SQUERYL("play2bars-squeryl", "Play with Squeryl"),
    PLAY_HEROKU_SEED("play-heroku-seed", "Play, Heroku and PostgreSQL seed."),
    SLICK_SORTABLE("slick-sortable", "Play Framework with Slick back-end for JQuery UI Sortable"),
    PLAY_MULTIDOMAIN_SEED("play-multidomain-seed", "Play 2.4 Multidomain Seed"),
    MICROSERVICES_SEED_PROJECT("microservices-seed-project", "Microservices Seed Project"),
    PLAY_JAVA_PREVIEW("play-java-preview", "Play Java Seed (Preview)"),
    PLAY_ANGULAR_REQUIRE_SEED("play-angular-require-seed", "Play Framework, AngularJS, WebJars, and RequireJS Seed"),
    SKALHOLT("skalholt", "Skalholt Code Generator for Play Framework and Slick"),
    PLAYSLICK_QUICKSTART("play-slick-quickstart", "Play Slick quickstart"),
    PLAY_RESTFB_JABA("play-restfb-jaba", "RestFB sample for Play Framework"),
    PLAY_OAUTH2_SCALA("play-oauth2-scala", "Play Framework with OAuth2 API sample"),
    PLAY_ING_GRAVATAR("playing-gravatar", "Play with Gravatar Image"),
    PLAY_BIGPIPE_WITH_RXJAVA_HYSTRIX("play-bigpipe-with-rxjava-hystrix", "BigPipe using Play, RxJava, and Hystrix"),
    PLAY_SCALA_SCALAJS("play-scala-scalajs", "Play Scala ScalaJS"),
    SCALIKEJDBC_ACTIVATOR_TEMPLATE("scalikejdbc-activator-template", "Hello ScalikeJDBC!"),
    PLAYSCALA_INTRO_REACTIVE_PLATFORM_15V09("play-scala-intro-reactive-platform-15v09", "Play Scala Intro (Reactive Platform 15v09)"),
    REACTIVE_SALESFORCE_REST_JAVASCRIPT_SEED("reactive-salesforce-rest-javascript-seed", "Reactive Salesforce Seed with REST and JavaScript"),
    JAPILA_PLAY_SLICK_POSTGRESQL_SEED("japila-play-slick-postgresql-seed", "Japila Software's Play with Slick and PostgreSQL Seed"),
    WEBJARS_SAMPLE_PLAY2("webjars-sample-play2", "WebJars Sample for Play 2.x"),
    SLICK_PLAY_ANGULARJS_SECURESOCIAL_SEED("slick-play-angularjs-securesocial-seed", "Slick Play AngularJS SecureSocial Seed"),
    PLAY_YEOMAN("play-yeoman", "Play (Scala) with play-yeoman"),
    PLAY_SCALA_REACTIVE_PLATFORM_15V09("play-scala-reactive-platform-15v09", "Play Scala Seed (Reactive Platform 15v09)"),
    PLAY_SCALA_ANGULARJS_GULP("play-scala-angularjs-gulp", "Hello play-scala-angularjs-gulp template!"),
    PLAY_ROCA("play-roca", "ROCA example built with Play"),
    ANONYMOUS_CHAT("anonymous-chat", "Anonymous Chat"),
    HELLO_PLAY_2_3_SCALA("hello-play-2_3-scala", "Hello Play Framework 2.3 (Scala Only)"),
    PLAYJOOQ("playJooq", "Seed for Play with Jooq"),
    SIGNALJ_CHAT_JAVA("signalj-chat-java", "SignalJ Chat Demo in Java"),
    REACTIVE_MAPS_JAVA("reactive-maps-java", "Reactive Maps (Java 8)"),
    BANNER_ROULETTE("banner-roulette", "Webapp with play, scala, akka, redis, slick"),
    TWEETMAP_JAVA8("tweetmap-java8", "Tweetmap (Java 8)"),
    REACTIVE_STOCKS_JAVA8("reactive-stocks-java8", "Reactive Stocks (Java 8)"),
    HELLOvPLAY_SCALA("hello-play-scala", "Hello Play Framework (Scala Only)"),
    SECURESOCIAL_SLICK_BOOTSTRAP3_SAMPLE("securesocial-slick-bootstrap3-sample", "Play Slick Securesocial Bootstrap3 Reactive Quickstart"),
    HELLO_PLAY_JAVA("hello-play-java", "Hello Play Framework (Java Only)"),
    PLAY_ANGULARJS_WEBAPP_SEED("play-angularjs-webapp-seed", "Play AngularJS Webapp Seed"),
    PLAY_CAKE("play-cake", "Play Cake Pattern (Scala)"),
    PLAY_SILHOUETTE_ANGULAR_SEED("play-silhouette-angular-seed", "The Play Silhouette Angular Seed Project"),
    PLAY_SLICK_ANGULAR_TEST_EXAMPLE("play-slick-angular-test-example", "Play Slick AngularJS Bootstrap H2 Tests Example"),
    REALTIME_SEARCH("realtime-search", "Reactive Real-time Search"),
    PLAY_SCALA("play-scala", "Play Scala Seed"),
    SPARK_PLAY("spark-play", "Spark and Play"),
    MDTP_API_MICROSERVICE("mdtp-api-microservice", "MDTP API microservice"),
    PLAY_JAVA_DAGGER_DEPENDENCY_INJECTION("play-java-dagger-dependency-injection", "Play + Java + dagger"),
    MACWIRE_ACTIVATOR("macwire-activator", "No-framework Dependency Injection with MacWire and Play Activator"),
    PLAY_AKKA_CLUSTER_SAMPLE("play-akka-cluster-sample", "Play Framework Akka Cluster Frontend with AngularJS and RequireJS"),
    SCALDI_PLAY_EXAMPLE("scaldi-play-example", "Scaldi Play 2.4 Example"),
    PLAY_SCALA_BACKBONE_TODO("play-scala-backbone-todo", "Play Slick Backbone Todo List Example"),
    PLAY_REACTIVE_MONGO("play-reactive-mongo", "Play Framework with Reactive Mongo Driver"),
    PLAY_MODULARvMULTIPROJECT("play-modular-multiproject", "Play Modular Subprojects"),
    PLAY_GUICE("play-guice", "Play with Guice"),
    PLAY_JAVA_INTRO_REACTIVE_PLATFORM_15V09("play-java-intro-reactive-platform-15v09", "Play Java Intro (Reactive Platform 15v09)"),
    PLAYING_GOOGLE_RECAPTCHA("playing-google-recaptcha", "Play with Google reCAPTCHA"),
    REACTIVE_ORIENTATION("reactive-orientation", "HTML 5 Device Orientation with play, ember and websockets"),
    SCRUPAL_ACTIVATOR_SEED("scrupal-activator-seed", "Scrupal Module Seed Template"),
    REACTIVE_SOLAR_FARM_MONITOR("reactive-solar-farm-monitor", "Reactive Solar Farm Monitor"),
    PLAY_SLICK_ADVANCED("play-slick-advanced", "Play Slick with Typesafe IDs"),
    PLAY_WITH_APPSPOKES("play-with-appspokes", "Play Framework with AppSpokes"),
    NVWA_SCALA("nvwa-scala", "A general services-oriented template project based on AWS Stack."),
    PLAY_HIBERNATE("play-hibernate", "Play (Java) Framework 2.4.2 and Hibernate."),
    PLAY_FRAMEWORK_SCALA_SEED("play-framework-scala-seed", "PLay Scala seed"),
    REACTIVE_STOCKS("reactive-stocks", "Reactive Stocks"),
    SLICK_ACTIVE_RECORD("slick-active-record", "ActiveSlick tutorial"),
    PLAY_MULTIDOMAIN_AUTH("play-multidomain-auth", "Play 2.3 Multidomain Auth"),
    PLAY_JAVA_INTRO("play-java-intro", "Play Java Intro"),
    ACTIVATOR_PLAY_AUTOSOURCE_REACTIVEMONGO("activator-play-autosource-reactivemongo", "ReactiveMongo Play Autosource"),
    PLAY_TLS_EXAMPLE("play-tls-example", "Play Framework SSL/TLS Example"),
    REDIS_TWITTER_CLONE("redis-twitter-clone", "Event Driven Redis Twitter Clone"),
    PLAY2_3_SPRING_PLAYAUTHENTICATE_DEADBOLT2_AND_MONGO_WITH_MORPHIA("Play2.3-Spring-PlayAuthenticate-deadbolt2-and-mongo-with-morphia", "Authentication and authorization in a Play application"),
    SCALDI_PLAY_23_EXAMPLE("scaldi-play-23-example", "Scaldi Play 2.3 Example"),
    PLAY_API_REST_SEED("play-api-rest-seed", "Play 2.4 API REST Seed"),
    HELLO_PLAY_BACKBONE("hello-play-backbone", "Play Framework with Backbone.js"),
    SNAKEYARD("snakeyard", "Reactive Snake - Akka Actor and Web Socket Example"),
    PLAY_SCALA_PREVIEW("play-scala-preview", "Play Scala Seed (Preview)"),
    PLAY_SBT_LAYOUT_SEED("play-sbt-layout-seed", "Play Scala with Sbt Layout"),
    JUST_PLAY_JAVA("just-play-java", "Just Play Java"),
    PLAY_JAVA_INTRO_PREVIEW("play-java-intro-preview", "Play Java Intro (Preview)"),
    PLAYING_REACTIVE_MONGO("playing-reactive-mongo", "Play 2.4.x with ReactiveMongo, WebJars and Bootstrap"),
    ANGULAR_SEED_PLAY_JAVA("angular-seed-play-java", "The Play Angular Seed Project - Java version"),
    REACTIVE_WORKSHOP("reactive-workshop", "Reactive Workshop Template"),
    MDTP_FRONTEND_MICROSERVICE("mdtp-frontend-microservice", "MDTP Frontend microservice"),
    LUNATECH_SECURESOCIAL_POC("lunatech-securesocial-poc", "Play Framework with SecureSocial and Slick 2.0"),
    PLAY_JSMESSAGES("play-jsmessages", "Play with client side localized messages"),
    PLAY_SILHOUETTE_SLICKvSEED("play-silhouette-slick-seed", "The Play Silhouette Slick Seed Project"),
    REACTIVE_JAVA8_PLAY("reactive-java8-play", "Go Reactive with Java 8 & Play Framework"),
    AKKA_CIRCUIT_BREAKER_JAVA("akka-circuit-breaker-java", "Akka Circuit Breaker with Java!"),
    PLAY_SILHOUETTE_SEED_SLICK("play-silhouette-seed-slick", "A Play Silhouette Slick Seed Project"),
    PLAY_SCALA_2_3("play-scala-2.3", "Play 2.3 Scala Seed"),
    REACTIVE_INSTRUMENTS_WORKSHOP("reactive-instruments-workshop", "Reactive Instruments Workshop"),
    BOILERPLAY("boilerplay", "Boilerplay - a modern template application with all the latest toys"),
    PLAYING_REACTJS("playing-reactjs", "Starting with ReactJS, Play 2.4.x, Scala and Anorm"),
    PLAY_SLICK_BOOTSTRAP3("play-slick-bootstrap3", "Play Slick Bootstrap3"),
    PLAY23_SILHOUETTE2_SLICK2_SEED("play23-silhouette2-slick2-seed", "The Play Silhouette Slick Seed Project"),
    PLAY_SILHOUETTE_SEED("play-silhouette-seed", "The Play Silhouette Seed Project"),
    MAPSURFER_TEMPLATE("mapsurfer-template", "Module template for MapSurfer"),
    PLAY_2_4_CRUD_WITH_REACTIVE_MONGO("play-2.4-crud-with-reactive-mongo", "Generic Play 2.4 CRUD with Macwire and ReactiveMongo"),
    PLAY_WEB_PORTAL("play-web-portal", "Enterprise Cloud Web Portal"),
    ACTIVATOR_PLAY_TRACING("activator-play-tracing", "Play Tracing"),
    CLUSTERED_CHAT("clustered-chat", "Clustered Chat with Play Framework, Websockets and Akka Cluster"),
    PLAYSTARTAPP("PlayStartApp", "Play Start Application"),
    SANGRIA_PLAYGROUND("sangria-playground", "Sangria Playground"),
    REACTIVE_MAPS("reactive-maps", "Reactive Maps"),
    SKINNY_ORM_IN_PLAY("skinny-orm-in-play", "Play Framework with Skinny ORM"),
    PLAY_JAVA("play-java", "Play Java Seed"),
    RESUMABLE_PLAY_EXAMPLE("resumable-play-example", "Resumable.js Play Example"),
    COMPUTER_DATABASE_JAVA("computer-database-java", "Computer Database Java"),
    PLAY_JS_ACTIVE("play-js-active", "Play (Java) Framework 2.4.2 and JsFrameworks."),
    PLAY_WEBSOCKET("play-websocket", "Play Framework with Websocket implementation, statefull/stateless"),
    PLAY2_CRUD_ACTIVATOR("play2-crud-activator", "Play + Java + CRUD"),
    ANGULAR_SEED_PLAY("angular-seed-play", "The Play Angular Seed Project"),
    PLAY_JAVA_SPRING("play-java-spring", "Play + Java + Spring"),
    PLAY_2_3_HIGHLIGHTS("play-2.3-highlights", "Play 2.3 Highlights"),
    PLAY_SCALA_TEST("play-scala-test", "Play Scala Seed"),
    ADVANCE_TWEETMAP_JAVA8("advance-tweetmap-java8", "Advance Tweetmap (Java 8)"),
    PLAY_JAVA_REACT_SEED("play-java-react-seed", "Play2 Java React Seed"),
    PLAY_SLICK_CODEGEN_FLYWAY_SEED("play-slick-codegen-flyway-seed", "Play Framework with Slick codegen and Flyway"),
    PLAY_SYSTEM_MONITOR_WITH_CHART_JS("play-system-monitor-with-chart-js", "PlayFramework Reactive Charts"),
    SALESFORCE_CANVAS_SEED("salesforce-canvas-seed", "Salesforce Canvas Seed"),
    PLAY_MONGO_KNOCKOUT("play-mongo-knockout", "Play Reactive Mongo application with KnockoutJS frontend"),
    PLAY_SLICK("play-slick", "Super Slick Play"),
    PLAY_HBASE("play-hbase", "Play Framework + HBase"),
    JUST_PLAY_SCALA("just-play-scala", "Just Play Scala"),
    TWEETMAP_WORKSHOP("tweetmap-workshop", "Tweetmap Workshop Template"),
    SIGNALJ_CHAT_SCALA("signalj-chat-scala", "SignalJ Chat Demo in Scala");

    public final String name;
    public final String title;

    private ActivatorTemplateEnum(String name, String title) {
        this.name = name;
        this.title = title;
    }

    @Override
    public String toString() {
        return name + " [ " + title + " ]";
    }

}
